map_manager_server_node:
    ros__parameters:
        use_sim_time: True
        map_numbers: 2

        image1: mars_yard_traversability_areas_borders.pgm
        resolution1: 0.495556
        origin1: [ -0.495556, -0.495556, 0.000000]
        frame_id1: map
        topic_name1: map_terrain_types

        image2: mars_yard_traversability_areas_borders_slope.pgm
        resolution2: 0.495556
        origin2: [ -0.495556, -0.495556, 0.000000]
        frame_id2: map
        topic_name2: map_slope
